<?php

require __DIR__ . '/../vendor/autoload.php';

$app = require __DIR__ . '/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Pengguna;
use App\Models\Admin;
use App\Models\Supplier;
use App\Models\DetailProduk;
use App\Models\SupplierOrder;
use App\Models\SupplierOrderDetail;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

echo "Starting PO test...\n";

// Ensure admin exists
$adminUser = Pengguna::where('email', 'admin@example.com')->first();
if (! $adminUser) {
    $pw = password_hash('password', PASSWORD_BCRYPT);
    $adminUser = Pengguna::create([
        'nama_pengguna' => 'Admin Test',
        'username' => 'admin-test',
        'email' => 'admin@example.com',
        'no_telepon' => '081200000000',
        'sandi' => $pw,
        'role' => 'admin',
        'is_active' => 1,
    ]);
    echo "Created admin pengguna: {$adminUser->pengguna_id}\n";
}

$admin = Admin::firstOrCreate(['pengguna_id' => $adminUser->pengguna_id]);

// pick supplier
$supplier = Supplier::first();
if (! $supplier) {
    echo "No supplier found. Aborting.\n";
    exit(1);
}

$detail = DetailProduk::first();
if (! $detail) {
    echo "No detail_produk found. Aborting.\n";
    exit(1);
}

try {
    DB::beginTransaction();

    $kode_order = 'PO-' . now()->format('Ymd') . '-' . str_pad(SupplierOrder::whereDate('tanggal_order', today())->count() + 1, 3, '0', STR_PAD_LEFT);

    $po = SupplierOrder::create([
        'supplier_id' => $supplier->supplier_id,
        'admin_id' => $admin->admin_id,
        'kode_order' => $kode_order,
        'total_item' => 0,
        'total_harga' => 0,
        'status' => 'draft',
        'catatan' => 'Test PO generated by script',
        'tanggal_order' => now(),
    ]);

    $qty = 2;
    $harga = 50000;
    $subtotal = $qty * $harga;

    SupplierOrderDetail::create([
        'supplier_order_id' => $po->supplier_order_id,
        'detail_produk_id' => $detail->detail_produk_id,
        'qty' => $qty,
        'harga_beli' => $harga,
        'subtotal' => $subtotal,
    ]);

    $po->update([
        'total_item' => $qty,
        'total_harga' => $subtotal,
    ]);

    DB::commit();

    echo "PO created: ID={$po->supplier_order_id}, KODE={$po->kode_order}\n";
} catch (\Throwable $e) {
    DB::rollBack();
    echo "Failed to create PO: " . $e->getMessage() . "\n";
    exit(1);
}

// Show latest 3 supplier_order rows
$rows = DB::select('SELECT * FROM supplier_order ORDER BY supplier_order_id DESC LIMIT 3');

echo "\nLatest supplier_order rows:\n";
print_r($rows);

echo "\nDone.\n";